[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python manage.py migrate && gunicorn trustscore.wsgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 100
