# Generated by Django 4.2.28 on 2026-02-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, help_text="The evaluated user's identifier.", max_length=100)),
                ('trust_score', models.IntegerField(help_text='Calculated trust score (0–100).')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=6)),
                ('flags', models.JSONField(default=list, help_text='List of triggered rule descriptions.')),
                ('input_data', models.JSONField(help_text='Original request payload for auditability.')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_field', models.CharField(help_text="Input field name to evaluate (e.g. 'account_age_days').", max_length=100)),
                ('operator', models.CharField(choices=[('lt', 'Less Than'), ('gt', 'Greater Than'), ('eq', 'Equal To')], help_text='Comparison operator: lt, gt, or eq.', max_length=2)),
                ('threshold', models.FloatField(help_text='Threshold value for the comparison.')),
                ('deduction', models.IntegerField(help_text='Points to deduct when the rule triggers (positive number).')),
                ('description', models.CharField(help_text="Human-readable flag text (e.g. 'New account').", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Only active rules are evaluated.')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
